# 测试配置文件
# @author <a href="https://github.com/Liuhy54">Liuhy54</a>
# @from <a href="https://github.com/Liuhy54/haidati-public">ai答题平台海答题</a>
server:
  port: 8101
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/haidati
    username: root
    password: root
  # Redis 配置
  # todo 需替换配置
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
    password: 123456